# Generated by Django 4.1.4 on 2023-12-24 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0006_alter_globalsettings_flag_logo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='globalsettings',
            old_name='brochure_name',
            new_name='name_nepali',
        ),
        migrations.RemoveField(
            model_name='globalsettings',
            name='SiteBox',
        ),
        migrations.RemoveField(
            model_name='globalsettings',
            name='Siteinstagram',
        ),
        migrations.RemoveField(
            model_name='globalsettings',
            name='Sitelicence',
        ),
        migrations.RemoveField(
            model_name='globalsettings',
            name='Sitelinkdinlink',
        ),
        migrations.RemoveField(
            model_name='globalsettings',
            name='brochure',
        ),
        migrations.AlterField(
            model_name='globalsettings',
            name='SiteAddress',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='globalsettings',
            name='SiteContact',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='globalsettings',
            name='SiteName',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='globalsettings',
            name='Sitedescription',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='globalsettings',
            name='Sitefacebooklink',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='globalsettings',
            name='Sitetwitterlink',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='globalsettings',
            name='Siteyoutubelink',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
