# Generated by Django 4.1.4 on 2023-12-25 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0012_alter_navigation_page_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='navigation',
            name='caption',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
