# Generated by Django 4.1.4 on 2023-12-26 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0013_alter_navigation_caption'),
    ]

    operations = [
        migrations.AlterField(
            model_name='navigation',
            name='page_type',
            field=models.CharField(blank=True, choices=[('Home', 'Home'), ('Home/Banner', 'Home/Banner'), ('Notice', 'Notice'), ('About/introduction', 'About/introduction'), ('Associate Organization', 'Associate Organization'), ('Board of Directors', 'Board of Directors'), ('Chairman Message', 'Chairman Message'), ('Secretary Message', 'Secretary Message'), ('Bidhans', 'Bidhans'), ('News/Events', 'News/Events'), ('Issue/Campaigns', 'Issue/Campaigns'), ('Publications', 'Publications'), ('Membership Form', 'Membership Form'), ('Image_Gallery', 'Image_Gallery'), ('Video_Gallery', 'Video_Gallery'), ('Download', 'Download'), ('Press release', 'Press release'), ('Contact', 'Contact'), ('Features', 'Features'), ('Features_1', 'Features_1'), ('Home/Video', 'Home/Video'), ('Aboutus', 'Aboutus'), ('Aboutus_1', 'Aboutus_1'), ('Achievements', 'Achievements'), ('Achievements_1', 'Achievements_1'), ('Testimonials', 'Testimonials'), ('Blog', 'Blog'), ('Services', 'Services'), ('Vision', 'Vision'), ('Mission', 'Mission'), ('Objectives', 'Objectives'), ('Our Strength', 'Our Strength'), ('Research & Development', 'Research & Development'), ('Video_Gallery', 'Video_Gallery'), ('Gallery', 'Gallery'), ('Contact', 'Contact'), ('Group', 'Group'), ('Video', 'Video'), ('Blog_1', 'Blog_1'), ('Services_1', 'Services_1'), ('Client', 'Client'), ('Client/Title', 'Client/Title'), ('Our Team', 'Our Team'), ('OurTeam/Slider', 'OurTeam/Slider')], max_length=50, null=True),
        ),
    ]
