# Generated by Django 4.1.4 on 2023-12-26 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0015_alter_navigation_page_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='navigation',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
