# Generated by Django 4.1.4 on 2023-12-26 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0019_alter_navigation_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='navigation',
            name='date',
        ),
        migrations.AddField(
            model_name='navigation',
            name='published_date',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
