# Generated by Django 4.1.4 on 2023-12-26 08:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0020_remove_navigation_date_navigation_published_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='navigation',
            name='published_date',
        ),
        migrations.AddField(
            model_name='navigation',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, null=True),
        ),
    ]
