# Generated by Django 4.1.4 on 2023-12-26 08:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0021_remove_navigation_published_date_navigation_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='navigation',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, editable=False, null=True),
        ),
    ]
