# Generated by Django 4.1.4 on 2023-12-27 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0026_alter_navigation_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactus',
            old_name='mobileno',
            new_name='mobile',
        ),
    ]
