# Generated by Django 4.1.4 on 2023-12-27 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0027_rename_mobileno_contactus_mobile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactus',
            old_name='mobile',
            new_name='mobilenum',
        ),
    ]
