# Generated by Django 4.1.4 on 2023-12-27 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0028_rename_mobile_contactus_mobilenum'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactus',
            name='mobileno',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
