# Generated by Django 4.1.4 on 2023-12-28 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0033_alter_navigation_page_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='navigation',
            name='video_link',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
