# Generated by Django 5.0 on 2023-12-31 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0035_rename_name_nepali_globalsettings_siteregister_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='globalsettings',
            name='Sitelicence',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
