# Generated by Django 5.0 on 2023-12-31 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0036_alter_globalsettings_sitelicence'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='navigation',
            name='desc',
        ),
        migrations.AddField(
            model_name='navigation',
            name='short_desc1',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='navigation',
            name='page_type',
            field=models.CharField(blank=True, choices=[('Home', 'Home'), ('Home/Banner', 'Home/Banner'), ('Home/Video', 'Home/Video'), ('About Us', 'About Us')], max_length=50, null=True),
        ),
    ]
