# Generated by Django 5.0 on 2024-01-02 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0039_globalsettings_contacttitle_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='globalsettings',
            old_name='ContactTitle',
            new_name='ContactTitle2',
        ),
    ]
