# Generated by Django 5.0 on 2024-01-02 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0040_rename_contacttitle_globalsettings_contacttitle2'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalsettings',
            name='EstablishedDate',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
