# Generated by Django 5.0 on 2024-01-02 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0041_globalsettings_establisheddate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='navigation',
            name='video',
        ),
        migrations.RemoveField(
            model_name='navigation',
            name='video_link',
        ),
    ]
