# Generated by Django 5.0 on 2024-01-05 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0042_remove_navigation_video_remove_navigation_video_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='navigation',
            name='short_desc2',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='navigation',
            name='short_desc3',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='navigation',
            name='page_type',
            field=models.CharField(blank=True, choices=[('Home', 'Home'), ('Home/Banner', 'Home/Banner'), ('Home/Video', 'Home/Video'), ('About Us', 'About Us'), ('MESSAGE FROM CHAIRMAN', 'MESSAGE FROM CHAIRMAN'), ('MESSAGE FROM DIRECTOR', 'MESSAGE FROM DIRECTOR'), ('Our Valuable Clients', 'Our Valuable Clients'), ('Sectors We Work In', 'Sectors We Work In'), ('Operating Procedure', 'Operating Procedure'), ('What Our Clients Say', 'What Our Clients Say'), ('Our Clients', 'Our Clients'), ('Countries', 'Countries'), ('License', 'License'), ('Newspaper', 'Newspaper'), ('About Nepal', 'About Nepal'), ('Gallery', 'Gallery'), ('Our Strengths', 'Our Strengths'), ('Diverse sectors', 'Diverse sectors'), ('Training facility', 'Training facility'), ('Dedicated database', 'Dedicated database'), ('Connect talents', 'Connect talents'), ('Skill test programs', 'Skill test programs'), ('Excellent management', 'Excellent management'), ('Ethical Recruitment', 'Ethical Recruitment'), ('Respect human rights', 'Respect human rights'), ('About Us1', 'About Us1'), ('Choose Us', 'Choose Us'), ('Our Mission', 'Our Mission'), ('Our Vision', 'Our Vision'), ('Latest Jobs', 'Latest Jobs')], max_length=50, null=True),
        ),
    ]
