# Generated by Django 5.0 on 2024-01-05 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0043_navigation_short_desc2_navigation_short_desc3_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='navigation',
            name='short_desc2',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='navigation',
            name='short_desc3',
            field=models.TextField(null=True),
        ),
    ]
