# Generated by Django 5.0 on 2024-01-05 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0044_alter_navigation_short_desc2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='navigation',
            name='short_desc3',
        ),
    ]
