# Generated by Django 5.0 on 2024-01-05 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0045_remove_navigation_short_desc3'),
    ]

    operations = [
        migrations.AddField(
            model_name='navigation',
            name='short_desc3',
            field=models.TextField(null=True),
        ),
    ]
