# Generated by Django 5.0 on 2024-01-05 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0046_navigation_short_desc3'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='navigation',
            name='meta_keyword',
        ),
        migrations.RemoveField(
            model_name='navigation',
            name='meta_title',
        ),
    ]
