# Generated by Django 5.0 on 2024-01-05 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0047_remove_navigation_meta_keyword_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='navigation',
            name='meta_keyword',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='navigation',
            name='meta_title',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
