# Generated by Django 5.0 on 2024-01-08 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0048_navigation_meta_keyword_navigation_meta_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplyNow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_code', models.CharField(max_length=10, unique=True)),
                ('full_name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=255)),
                ('nationality', models.CharField(max_length=50)),
                ('passport_number', models.CharField(max_length=20, unique=True)),
                ('Gender', models.CharField(max_length=100)),
                ('place_of_issue', models.CharField(max_length=100)),
                ('expiry_date', models.DateField()),
                ('date_of_birth', models.DateField()),
                ('height', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('marital_status', models.CharField(max_length=100)),
                ('children', models.PositiveIntegerField(default=0)),
                ('religion', models.CharField(blank=True, max_length=50, null=True)),
                ('arabic_speaking', models.CharField(max_length=100)),
                ('arabic_listening', models.CharField(max_length=100)),
                ('arabic_reading', models.CharField(max_length=100)),
                ('arabic_writing', models.CharField(max_length=100)),
                ('english_speaking', models.CharField(max_length=100)),
                ('english_listening', models.CharField(max_length=100)),
                ('english_reading', models.CharField(max_length=100)),
                ('english_writing', models.CharField(max_length=100)),
                ('hindi_speaking', models.CharField(max_length=100)),
                ('hindi_listening', models.CharField(max_length=100)),
                ('hindi_reading', models.CharField(max_length=100)),
                ('hindi_writing', models.CharField(max_length=100)),
                ('education_level', models.CharField(max_length=50)),
                ('working_field_nepal', models.CharField(max_length=50)),
                ('employer_nepal', models.CharField(max_length=50)),
                ('duration_nepal', models.CharField(max_length=100)),
                ('address_nepal', models.TextField()),
                ('working_field_overseas', models.CharField(max_length=50)),
                ('employer_overseas', models.CharField(max_length=50)),
                ('duration_overseas', models.CharField(max_length=100)),
                ('address_overseas', models.TextField()),
                ('other_skills', models.CharField(max_length=100, unique=True)),
                ('agents_name', models.CharField(max_length=100)),
                ('own_phone_number', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('home_phone_number', models.CharField(max_length=15)),
                ('relatives_phone_number', models.CharField(max_length=15)),
            ],
        ),
        migrations.DeleteModel(
            name='Membership',
        ),
    ]
