# Generated by Django 5.0 on 2024-01-09 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0049_applynow_delete_membership'),
    ]

    operations = [
        migrations.RenameField(
            model_name='applynow',
            old_name='Gender',
            new_name='gender',
        ),
        migrations.AlterField(
            model_name='applynow',
            name='other_skills',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
