# Generated by Django 5.0 on 2024-01-09 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0050_rename_gender_applynow_gender_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='applynow',
            old_name='agents_name',
            new_name='agentName',
        ),
        migrations.RenameField(
            model_name='applynow',
            old_name='address_overseas',
            new_name='country_overseas',
        ),
        migrations.RenameField(
            model_name='applynow',
            old_name='date_of_birth',
            new_name='dateOfBirth',
        ),
        migrations.RenameField(
            model_name='applynow',
            old_name='education_level',
            new_name='education',
        ),
        migrations.RenameField(
            model_name='applynow',
            old_name='expiry_date',
            new_name='expiryDate',
        ),
        migrations.RenameField(
            model_name='applynow',
            old_name='working_field_nepal',
            new_name='field_nepal',
        ),
        migrations.RenameField(
            model_name='applynow',
            old_name='working_field_overseas',
            new_name='field_overseas',
        ),
        migrations.RenameField(
            model_name='applynow',
            old_name='full_name',
            new_name='fullName',
        ),
        migrations.RenameField(
            model_name='applynow',
            old_name='home_phone_number',
            new_name='homeNumber',
        ),
        migrations.RenameField(
            model_name='applynow',
            old_name='job_code',
            new_name='jobCode',
        ),
        migrations.RenameField(
            model_name='applynow',
            old_name='marital_status',
            new_name='maritalStatus',
        ),
        migrations.RenameField(
            model_name='applynow',
            old_name='other_skills',
            new_name='otherSkills',
        ),
        migrations.RenameField(
            model_name='applynow',
            old_name='passport_number',
            new_name='passportNumber',
        ),
        migrations.RenameField(
            model_name='applynow',
            old_name='own_phone_number',
            new_name='phoneNumber',
        ),
        migrations.RenameField(
            model_name='applynow',
            old_name='place_of_issue',
            new_name='placeOfIssue',
        ),
        migrations.RenameField(
            model_name='applynow',
            old_name='relatives_phone_number',
            new_name='relativesNumber',
        ),
    ]
