# Generated by Django 5.0 on 2024-01-10 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0053_alter_navigation_meta_keyword_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='navigation',
            name='brochure',
        ),
        migrations.RemoveField(
            model_name='navigation',
            name='icon_image',
        ),
        migrations.RemoveField(
            model_name='navigation',
            name='image',
        ),
        migrations.RemoveField(
            model_name='navigation',
            name='short_desc2',
        ),
        migrations.RemoveField(
            model_name='navigation',
            name='short_desc3',
        ),
        migrations.RemoveField(
            model_name='navigation',
            name='slider_image',
        ),
    ]
